feedback_plugin/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', 'feedback_plugin.views.feedback_view', name='feedback'),
)

website/urls.py
from cms.sitemaps import CMSSitemap
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^feedback/', include('feedback_plugin.urls', namespace='feedback')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

feedback_plugin/models.py
from django.db import models

from cms.models import CMSPlugin


class FeedbackPlugin(CMSPlugin):
    email_1 = models.EmailField(max_length=255, null=True, blank=True)
    email_2 = models.EmailField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return '%s, %s' % (self.email_1, self.email_2)


class FeedbackItem(models.Model):
    plugin_data = models.ForeignKey(FeedbackPlugin)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

item_plugin/models.py
# coding: utf-8
from django.db import models
from django.conf import settings

from cms.models import CMSPlugin


class ItemPlugin(CMSPlugin):
    template_name = models.CharField(max_length=255, choices=settings.CMS_ITEM_TEMPLATES)

    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    picture = models.ImageField(upload_to='item_plugin/picture', null=True, blank=True)
    big_picture = models.ImageField(upload_to='item_plugin/big_picture', null=True, blank=True)
    awesome_icon = models.CharField(max_length=255, null=True, blank=True)

    category = models.CharField(max_length=255, null=True, blank=True)
    client = models.CharField(max_length=255, null=True, blank=True)
    date = models.DateTimeField(null=True, blank=True)
    
    twitter = models.CharField(max_length=255, null=True, blank=True)
    facebook = models.CharField(max_length=255, null=True, blank=True)
    vk = models.CharField(max_length=255, null=True, blank=True)
    linkedin = models.CharField(max_length=255, null=True, blank=True)
    
    def __unicode__(self):
        return u'%s - %s' % (self.get_template_name_display(), self.title)

   
        

feedback_plugin/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext as _ul

from website.utils import form_fields_to_bootstrap

from feedback_plugin.models import FeedbackItem


class FeedbackForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.plugin_data = kwargs.pop('plugin_data', None)
        super(FeedbackForm, self).__init__(*args, **kwargs)
        form_fields_to_bootstrap(self.fields)
        self.fields['name'].widget.attrs['placeholder'] = _ul(u'Ваше имя *')
        self.fields['phone'].widget.attrs['placeholder'] = _ul(u'Ваш телефон или email *')
    
    def save(self, *args, **kwargs):
        self.instance.plugin_data = self.plugin_data
        return super(FeedbackForm, self).save(*args, **kwargs)

    class Meta:
        model = FeedbackItem
        fields = ('name', 'phone',)

feedback_plugin/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages
from django.http import Http404
from django.utils.translation import ugettext as _ul

from feedback_plugin.models import FeedbackPlugin
from feedback_plugin.forms import FeedbackForm


#http://ivanishchev.ru/
def feedback_view(request, pk):
    context = {}
    form_class = FeedbackForm
    next = request.GET.get('next', '/')

    if request.method == "POST":
        form = form_class(request.POST, plugin_data=get_object_or_404(FeedbackPlugin, pk=pk))
        if form.is_valid():
            form.save()
            messages.success(request, _ul('Success. Your request has been sent to our team. Please waiting our response.'), extra_tags='feedback')
        else:
            messages.error(request, _ul('Error. Your request has not been sent to our team. Please enter all fields correctly.'), extra_tags='feedback')
        return redirect(next)
    raise Http404

feedback_plugin/templates/feedback_plugin/feedback_plugin.html
{% load i18n %}

<form name="sentMessage" id="contactForm" method="post" action="{% url 'feedback:feedback' instance.pk %}">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                {{feedback_form.name}}
            </div>
            <div class="form-group">
                {{feedback_form.phone}}
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-lg-12">
       
            <div id="success"></div>
            <button type="submit" class="btn btn-xl"><i class="fa fa-tty"></i> {% trans 'Связаться со мной' %}</button>
        </div>
    </div>
</form>

portfolio_landpage/templates/portfolio_landpage/data_about.html
<ul class="timeline">
<li class="timeline-inverted">
    <div class="timeline-image">
        {% if instance.picture %}        
            <img class="img-circle img-responsive" src="/media/{{instance.picture}}" alt="">
        {% else %}
            <div class="awesome-img">
            <i class="fa {{instance.awesome_icon}} fa-inverse"></i>
            </div>
        {% endif %}
    </div>
    <div class="timeline-panel">
        <div class="timeline-heading">
            <h4 class="subheading"><br><br>{{instance.title}}</h4>
        </div>
        <div class="timeline-body">
            <p class="text-muted">{{instance.description|safe}}</p>
        </div>
    </div>
</li>
</ul>

{% comment %}
<li>
    <div class="timeline-image">
        <img class="img-circle img-responsive" src="{% static 'portfolio_landpage/img/about/1.jpg' %}" alt="">
    </div>
    <div class="timeline-panel">
        <div class="timeline-heading">
            <h4>2009-2011</h4>
            <h4 class="subheading">Our Humble Beginnings</h4>
        </div>
        <div class="timeline-body">
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
        </div>
    </div>
</li>
<li class="timeline-inverted">
    <div class="timeline-image">
        <img class="img-circle img-responsive" src="{% static 'portfolio_landpage/img/about/2.jpg' %}" alt="">
    </div>
    <div class="timeline-panel">
        <div class="timeline-heading">
            <h4>March 2011</h4>
            <h4 class="subheading">An Agency is Born</h4>
        </div>
        <div class="timeline-body">
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
        </div>
    </div>
</li>
<li>
    <div class="timeline-image">
        <img class="img-circle img-responsive" src="{% static 'portfolio_landpage/img/about/3.jpg' %}" alt="">
    </div>
    <div class="timeline-panel">
        <div class="timeline-heading">
            <h4>December 2012</h4>
            <h4 class="subheading">Transition to Full Service</h4>
        </div>
        <div class="timeline-body">
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
        </div>
    </div>
</li>
<li class="timeline-inverted">
    <div class="timeline-image">
        <img class="img-circle img-responsive" src="{% static 'portfolio_landpage/img/about/4.jpg' %}" alt="">
    </div>
    <div class="timeline-panel">
        <div class="timeline-heading">
            <h4>July 2014</h4>
            <h4 class="subheading">Phase Two Expansion</h4>
        </div>
        <div class="timeline-body">
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
        </div>
    </div>
</li>
<li class="timeline-inverted">
    <div class="timeline-image">
        <h4>Be Part
            <br>Of Our
            <br>Story!</h4>
    </div>
</li>
{% endcomment %}

portfolio_landpage/templates/portfolio_landpage/data_clients.html
<div class="col-md-3 col-sm-6">
    <a href="#">
        <img src="/media/{{instance.picture}}" class="img-responsive img-centered" alt="">
    </a>
</div>

{% comment %}
<div class="col-md-3 col-sm-6">
    <a href="#">
        <img src="{% static 'portfolio_landpage/img/logos/envato.jpg' %}" class="img-responsive img-centered" alt="">
    </a>
</div>
<div class="col-md-3 col-sm-6">
    <a href="#">
        <img src="{% static 'portfolio_landpage/img/logos/designmodo.jpg' %}" class="img-responsive img-centered" alt="">
    </a>
</div>
<div class="col-md-3 col-sm-6">
    <a href="#">
        <img src="{% static 'portfolio_landpage/img/logos/themeforest.jpg' %}" class="img-responsive img-centered" alt="">
    </a>
</div>
<div class="col-md-3 col-sm-6">
    <a href="#">
        <img src="{% static 'portfolio_landpage/img/logos/creative-market.jpg' %}" class="img-responsive img-centered" alt="">
    </a>
</div>
{% endcomment %}

portfolio_landpage/templates/portfolio_landpage/data_service.html
<div class="col-md-4">
    <span class="fa-stack fa-4x">
        <i class="fa fa-circle fa-stack-2x text-primary"></i>
        <i class="fa {{instance.awesome_icon}} fa-stack-1x fa-inverse"></i>
    </span>
    <h4 class="service-heading">{{instance.title}}</h4>
    <p class="text-muted">{{instance.description|safe}}</p>
</div>


{% comment %}
<div class="col-md-4">
    <span class="fa-stack fa-4x">
        <i class="fa fa-circle fa-stack-2x text-primary"></i>
        <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
    </span>
    <h4 class="service-heading">E-Commerce</h4>
    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
</div>
<div class="col-md-4">
    <span class="fa-stack fa-4x">
        <i class="fa fa-circle fa-stack-2x text-primary"></i>
        <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
    </span>
    <h4 class="service-heading">Responsive Design</h4>
    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
</div>
<div class="col-md-4">
    <span class="fa-stack fa-4x">
        <i class="fa fa-circle fa-stack-2x text-primary"></i>
        <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
    </span>
    <h4 class="service-heading">Web Security</h4>
    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
</div>
{% endcomment %}

portfolio_landpage/templates/portfolio_landpage/data_team.html
<div class="col-sm-4">
</div>
<div class="col-sm-4">
    <div class="team-member">
        {% if instance.picture %}        
        <img src="/media/{{instance.picture}}" class="img-responsive img-circle" alt="">
        {% endif %}
        <h4>{{instance.title}}</h4>
        <p class="text-muted">{{instance.category}}</p>
        {% comment %}
        <ul class="list-inline social-buttons">
            <li><a href="{{instance.twitter}}"><i class="fa fa-twitter"></i></a>
            </li>
            <li><a href="{{instance.facebook}}"><i class="fa fa-facebook"></i></a>
            </li>
            <li><a href="{{instance.linkedin}}"><i class="fa fa-linkedin"></i></a>
            </li>
        </ul>
        {% endcomment %}
    </div>
</div>



{% comment %}
<div class="col-sm-4">
    <div class="team-member">
        <img src="{% static 'portfolio_landpage/img/team/1.jpg' %}" class="img-responsive img-circle" alt="">
        <h4>Kay Garland</h4>
        <p class="text-muted">Lead Designer</p>
        <ul class="list-inline social-buttons">
            <li><a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li><a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a>
            </li>
        </ul>
    </div>
</div>
<div class="col-sm-4">
    <div class="team-member">
        <img src="{% static 'portfolio_landpage/img/team/2.jpg' %}" class="img-responsive img-circle" alt="">
        <h4>Larry Parker</h4>
        <p class="text-muted">Lead Marketer</p>
        <ul class="list-inline social-buttons">
            <li><a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li><a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a>
            </li>
        </ul>
    </div>
</div>
<div class="col-sm-4">
    <div class="team-member">
        <img src="{% static 'portfolio_landpage/img/team/3.jpg' %}" class="img-responsive img-circle" alt="">
        <h4>Diana Pertersen</h4>
        <p class="text-muted">Lead Developer</p>
        <ul class="list-inline social-buttons">
            <li><a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li><a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a>
            </li>
        </ul>
    </div>
</div>
{% endcomment %}

portfolio_landpage/templates/portfolio_landpage/portfolio_base.html
{% load i18n %}
{% load staticfiles %}
{% load cms_tags menu_tags sekizai_tags %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="{{current_site.name}}">
    <meta name="description" content="{% page_attribute meta_description %}"/>
    <meta name="keywords" content="{% page_attribute meta_keywords %}"/>

    <title>{% block title %}{% page_attribute 'title' %}{% endblock title %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'portfolio_landpage/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'portfolio_landpage/css/portfolio.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'portfolio_landpage/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% render_block "css" %}

</head>

<body id="page-top" class="index">
    {% cms_toolbar %}   
    
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">{{current_site.name}}</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                   {% block menu-links %}
                    <li>
                        <a class="page-scroll" href="#services">{% placeholder "services-header" %}</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">{% placeholder "portfolio-header" %}</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">{% placeholder "about-header" %}</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team">{% placeholder "team-header" %}</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">{% placeholder "contact-header" %}</a>
                    </li>
                    {% endblock %}
                    
                    {% show_menu 0 100 100 100 %}
                    
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'admin:logout' %}?next=/"><i class="fa fa-toggle-off"></i></a>
                    </li>
                    {% else %}
                    <li>
                        <a href="?edit"><i class="fa fa-toggle-on"></i></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block header %}
    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">{% placeholder "intro-lead-in" %}</div>
                <div class="intro-heading">{% placeholder "intro-heading" %}</div>
                <a href="#contact" class="page-scroll btn btn-xl"><i class="fa fa-hand-o-up"></i> {% placeholder "intro-button" %}</a>
            </div>
        </div>
    </header>
    {% endblock %}

    {% block container %}{% endblock %}

    {% block footer %}
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; {{current_site.name}} {% now "Y" %}</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        {% comment %}
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                        {% endcomment %}
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        {% comment %}
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                        {% endcomment %}
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}

    {% render_block "js" %}

    <!-- jQuery -->
    <script src="{% static 'portfolio_landpage/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'portfolio_landpage/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'portfolio_landpage/js/classie.js' %}"></script>
    <script src="{% static 'portfolio_landpage/js/cbpAnimatedHeader.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'portfolio_landpage/js/jqBootstrapValidation.js' %}"></script>
    {# <script src="{% static 'portfolio_landpage/js/contact_me.js' %}"></script> #}

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'portfolio_landpage/js/portfolio.js' %}"></script>


</body>

</html>

portfolio_landpage/templates/portfolio_landpage/portfolio_landpage.html
{% extends 'portfolio_landpage/portfolio_base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load cms_tags menu_tags sekizai_tags %}


{% block container %}
    <!-- Services Section -->
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">{% placeholder "services-header" %}</h2>
                    <h3 class="section-subheading text-muted">{% placeholder "services-subheader" %}</h3>
                </div>
            </div>
            <div class="row text-center">
                {% placeholder "services-data" %}
            </div>
        </div>
    </section>

    <!-- Portfolio Grid Section -->
    <section id="portfolio" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">{% placeholder "portfolio-header" %}</h2>
                    <h3 class="section-subheading text-muted">{% placeholder "portfolio-subheader" %}</h3>
                </div>
            </div>
            <div class="row">
                {% placeholder "portfolio-data" %}
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">{% placeholder "about-header" %}</h2>
                    <h3 class="section-subheading text-muted">{% placeholder "about-subheader" %}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    {% placeholder "about-data" %}
                </div>
            </div>
        </div>
    </section>

    <!-- Team Section -->
    <section id="team" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">{% placeholder "team-header" %}</h2>
                    <h3 class="section-subheading text-muted">{% placeholder "team-subheader" %}</h3>
                </div>
            </div>
            <div class="row">
                {% placeholder "team-data" %}
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <p class="large text-muted">{% placeholder "team-bottom" %}</p>
                    {%comment%}
                    <br>
                    <br>
                    <p class="large text-muted">{% placeholder "team-social" %}</p>
                    <ul class="list-inline social-buttons">
                        <li><a href='{% placeholder "team-vk-url" %}'><i class="fa fa-vk"></i></a></li>
                    </ul>
                    {% endcomment %}
                </div>
            </div>
        </div>
    </section>

    <!-- Clients Aside -->
    <aside class="clients">
        <div class="container">
            <div class="row">
                {% placeholder "clients-data" %}
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">{% placeholder "contact-header-other" %}</h2>
                    <h3 class="section-subheading text-muted">{% placeholder "contact-subheader" %}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="section-heading">{% placeholder "phones-header" %}</h4>
                            <span class="section-heading" style="font-size: 18px;"><i class="fa fa-phone"></i> {% placeholder "phone-1" %}</span>
                            {% comment %}
                            <br>
                            <span class="section-heading" style="font-size: 18px;"><i class="fa fa-phone"></i> {% placeholder "phone-2" %}</span>
                            <br>
                            <br>
                            {% endcomment %}
                            <br>
                            <h4 class="section-heading">{% placeholder "emails-header" %}</h4>
                            <span class="section-heading" style="font-size: 16px;"><i class="fa fa-envelope-o"></i> {% placeholder "email-1" %}</span>
                            {% comment %}
                            <br>
                            <span class="section-heading" style="font-size: 16px;"><i class="fa fa-envelope-o"></i> {% placeholder "email-2" %}</span>
                            <br>
                            <br>
                            {% endcomment %}
                        </div>
                        <div class="col-md-6">
                            {% placeholder "feedback-form-data" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

portfolio_landpage/templates/portfolio_landpage/portfolio_notes.html
{% extends 'portfolio_landpage/portfolio_base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load cms_tags menu_tags sekizai_tags %}

{% block menu-links %}
    <li>
        <a class="page-scroll" href="/">{% trans 'На сайт' %}</a>
    </li>
{% endblock %}

{% block header %}
    <!-- Header -->
    <header>
        <div class="container" style="height: 100px;">
            <div class="intro-text">
            </div>
        </div>
    </header>
{% endblock %}

{% block container %}
    <section id="services" style="padding: 150px;">
        {% placeholder "notes" %}
    </section>
{% endblock %}

{% block footer %}
{% endblock %}

website/templates/base.html
{% load cms_tags menu_tags sekizai_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}This is my new project home page{% endblock title %}</title>
    {% render_block "css" %}
    <style type="text/css">
        .nav {
            padding-left: 0;
        }
        .nav li {
            display: inline;
            list-style-type: none;
            padding-right: 20px;
        }
    </style>
</head>
<body>
{% cms_toolbar %}
<div style="width: 940px; margin:0 auto">
    <ul class="nav">
        {% show_menu 0 100 100 100 %}
    </ul>
    {% block content %}
    {% endblock content %}
</div>
{% render_block "js" %}
</body>
</html>

website/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block content %}
	{% placeholder "content" %}
{% endblock content %}

website/templates/sidebar_left.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block content %}
    <div style="width:20%; float:left;">
        {% placeholder "sidebar" %}
    </div>
    <div style="width:80%; float:left;">
        {% placeholder "content" %}
    </div>
{% endblock content %}

website/templates/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block content %}
    <div style="width:80%; float:left;">
        {% placeholder "content" %}
    </div>
    <div style="width:20%; float:left;">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}